
#DEVELOPED BY MYMINES
version: "3"
services:

  mc:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
      - ./mods:/mods:ro
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DEBUG: "true"
      VERSION: "1.20.2"
      DIFFICULTY: "HARD"
      SERVER_NAME: "teste"
      ALLOW_FLIGHT: "true"
      MAX_MEMORY: "3G"
      ONLINE_MODE: "false"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ENABLE_WHITELIST: "FALSE"
      ENFORE_WHITELIST: "FALSE"
      LOG_TIMESTAMP: "true"
      SNOOPER_ENABLED: "false"

    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  data: {}


 

        